<a href="https://colab.research.google.com/github/rishiraj09/pytorch-tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tensors

* A torch. Tensor is a multi-dimensional matrix containing elements of a single data type.
* Similar to Numpy Array, but full of fun things that make them workl better on GPU's(vs regular CPU's)
* default data type of float32.
* More suitable for deep learning than a numpy array.

In [1]:
import torch
import numpy as np

In [3]:
torch.__version__

'2.6.0+cu124'

### List

In [5]:
my_list = [[1,2,3,4,5,],[6,7,8,9,0]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]]

### Numpy Arrays

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.01520215, 0.63917999, 0.97242902, 0.16049329],
       [0.22146358, 0.10757626, 0.84338856, 0.16526913],
       [0.55543499, 0.72940927, 0.34305529, 0.30379031]])

In [8]:
np1.dtype

dtype('float64')

### Tensors

In [9]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.3255,  0.1097,  0.2827, -0.2999],
        [-1.1242,  0.1752,  0.5507,  0.3100],
        [ 1.8053, -2.1887,  0.4426,  1.0741]])

In [10]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0152, 0.6392, 0.9724, 0.1605],
        [0.2215, 0.1076, 0.8434, 0.1653],
        [0.5554, 0.7294, 0.3431, 0.3038]], dtype=torch.float64)